



// 标记当前呈现实例以进行资产解析
// 例如:resolveComponent、resolveDirective
export let currentRenderingInstance:  null = null
export let currentScopeId: string | null = null

/**
 * Set scope id when creating hoisted vnodes.
 * @private compiler helper
 */
export function pushScopeId(id: string | null) {
    currentScopeId = id
  }

/**
 * Technically we no longer need this after 3.0.8 but we need to keep the same
 * API for backwards compat w/ code generated by compilers.
 * @private
 */
export function popScopeId() {
    currentScopeId = null
  }